export const MARKETPLACE_START = 'MARKETPLACE_START';
export const DEFAULT_LAYOUT = 'DEFAULT_LAYOUT';
export const ITEM_FETCH_REQUEST = 'ITEM_FETCH_REQUEST';
export const ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS';
export const ITEM_FETCH_FAIL = 'ITEM_FETCH_FAIL';
export const ITEM_UPDATE_REQUEST = 'ITEM_UPDATE_REQUEST';
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS';
export const ITEM_UPDATE_FAIL = 'ITEM_UPDATE_FAIL';
